# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_pb2 as cloud__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CivicCloudServiceStub(object):
    """--- SERVICE DEFINITION ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/cloud.CivicCloudService/Login',
                request_serializer=cloud__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.VerifyOTP = channel.unary_unary(
                '/cloud.CivicCloudService/VerifyOTP',
                request_serializer=cloud__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=cloud__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.RegisterInit = channel.unary_unary(
                '/cloud.CivicCloudService/RegisterInit',
                request_serializer=cloud__pb2.RegisterInitRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.RegisterVerify = channel.unary_unary(
                '/cloud.CivicCloudService/RegisterVerify',
                request_serializer=cloud__pb2.RegisterVerifyRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/cloud.CivicCloudService/GetNodes',
                request_serializer=cloud__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=cloud__pb2.NodesResponse.FromString,
                _registered_method=True)
        self.StoreProjectDocument = channel.unary_unary(
                '/cloud.CivicCloudService/StoreProjectDocument',
                request_serializer=cloud__pb2.StoreProjectDocumentRequest.SerializeToString,
                response_deserializer=cloud__pb2.StoreProjectDocumentResponse.FromString,
                _registered_method=True)
        self.GetProjectDocument = channel.unary_unary(
                '/cloud.CivicCloudService/GetProjectDocument',
                request_serializer=cloud__pb2.GetProjectDocumentRequest.SerializeToString,
                response_deserializer=cloud__pb2.GetProjectDocumentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/cloud.CivicCloudService/HealthCheck',
                request_serializer=cloud__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=cloud__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetAdminStats = channel.unary_unary(
                '/cloud.CivicCloudService/GetAdminStats',
                request_serializer=cloud__pb2.AdminStatsRequest.SerializeToString,
                response_deserializer=cloud__pb2.AdminStatsResponse.FromString,
                _registered_method=True)
        self.ToggleNode = channel.unary_unary(
                '/cloud.CivicCloudService/ToggleNode',
                request_serializer=cloud__pb2.ToggleNodeRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.AddNode = channel.unary_unary(
                '/cloud.CivicCloudService/AddNode',
                request_serializer=cloud__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.RemoveNode = channel.unary_unary(
                '/cloud.CivicCloudService/RemoveNode',
                request_serializer=cloud__pb2.RemoveNodeRequest.SerializeToString,
                response_deserializer=cloud__pb2.Response.FromString,
                _registered_method=True)
        self.GetNodeFiles = channel.unary_unary(
                '/cloud.CivicCloudService/GetNodeFiles',
                request_serializer=cloud__pb2.NodeFileRequest.SerializeToString,
                response_deserializer=cloud__pb2.NodeFilesResponse.FromString,
                _registered_method=True)


class CivicCloudServiceServicer(object):
    """--- SERVICE DEFINITION ---
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterVerify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreProjectDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminStats(self, request, context):
        """ADMIN RPCS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """DYNAMIC NODE RPCS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CivicCloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=cloud__pb2.LoginRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=cloud__pb2.VerifyOTPRequest.FromString,
                    response_serializer=cloud__pb2.TokenResponse.SerializeToString,
            ),
            'RegisterInit': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterInit,
                    request_deserializer=cloud__pb2.RegisterInitRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'RegisterVerify': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterVerify,
                    request_deserializer=cloud__pb2.RegisterVerifyRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=cloud__pb2.GetNodesRequest.FromString,
                    response_serializer=cloud__pb2.NodesResponse.SerializeToString,
            ),
            'StoreProjectDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreProjectDocument,
                    request_deserializer=cloud__pb2.StoreProjectDocumentRequest.FromString,
                    response_serializer=cloud__pb2.StoreProjectDocumentResponse.SerializeToString,
            ),
            'GetProjectDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectDocument,
                    request_deserializer=cloud__pb2.GetProjectDocumentRequest.FromString,
                    response_serializer=cloud__pb2.GetProjectDocumentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=cloud__pb2.HealthCheckRequest.FromString,
                    response_serializer=cloud__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetAdminStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminStats,
                    request_deserializer=cloud__pb2.AdminStatsRequest.FromString,
                    response_serializer=cloud__pb2.AdminStatsResponse.SerializeToString,
            ),
            'ToggleNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleNode,
                    request_deserializer=cloud__pb2.ToggleNodeRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=cloud__pb2.AddNodeRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'RemoveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNode,
                    request_deserializer=cloud__pb2.RemoveNodeRequest.FromString,
                    response_serializer=cloud__pb2.Response.SerializeToString,
            ),
            'GetNodeFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeFiles,
                    request_deserializer=cloud__pb2.NodeFileRequest.FromString,
                    response_serializer=cloud__pb2.NodeFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.CivicCloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.CivicCloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CivicCloudService(object):
    """--- SERVICE DEFINITION ---
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/Login',
            cloud__pb2.LoginRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/VerifyOTP',
            cloud__pb2.VerifyOTPRequest.SerializeToString,
            cloud__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/RegisterInit',
            cloud__pb2.RegisterInitRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterVerify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/RegisterVerify',
            cloud__pb2.RegisterVerifyRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/GetNodes',
            cloud__pb2.GetNodesRequest.SerializeToString,
            cloud__pb2.NodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreProjectDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/StoreProjectDocument',
            cloud__pb2.StoreProjectDocumentRequest.SerializeToString,
            cloud__pb2.StoreProjectDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/GetProjectDocument',
            cloud__pb2.GetProjectDocumentRequest.SerializeToString,
            cloud__pb2.GetProjectDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/HealthCheck',
            cloud__pb2.HealthCheckRequest.SerializeToString,
            cloud__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/GetAdminStats',
            cloud__pb2.AdminStatsRequest.SerializeToString,
            cloud__pb2.AdminStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/ToggleNode',
            cloud__pb2.ToggleNodeRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/AddNode',
            cloud__pb2.AddNodeRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/RemoveNode',
            cloud__pb2.RemoveNodeRequest.SerializeToString,
            cloud__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.CivicCloudService/GetNodeFiles',
            cloud__pb2.NodeFileRequest.SerializeToString,
            cloud__pb2.NodeFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
